import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
// Components //
import Button from './_button'
import Input from './_input'
import Video from './_video'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Clase 11</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <h1 className='titulo'>Bienvenidos a la Clase 11</h1>

        <div>
          <Button name="Boton1" />
          <Button name="Boton2" />
          <Input placeholder="Soy un Input" />
          <Input placeholder="Soy otro Input" />
        </div>
        
        <div>
          <Video width="420" height="270" src="https://www.w3schools.com/html/mov_bbb.mp4" />
        </div>

      </main>
    </>
  )
}
